keys:
  - &yubikey 3843C723C748227138A7EAA4F22E9E9D8F5CCE04
  - &backupServer age10qfac2ds60xwzrlyfrxvt5kv0gwjpxculsm33rck43npafrt6aks8z69re
  - &IonosVPS2 age190v5scsrpgkw4mues9nlsmwxcn5fw5jwg88pxlsh0xmw6q3kffns6r9eqq
  - &backupServerOffsite age1qzf4xf3r0zl7u8v0u6ct5uv78ejp9gapn8tnphw2a8q39rltceaq6c6n48
  - &Email age1mfzehz2uj6vv0y0lvcv2s5egpqfl6403r30x8v7drztc0tqwd9zq89kqg2
  - &Kanidm age17egct2kj27ze3046aqqje79jtcq0evpjmceehp6uyf3zvqnnayyqjpt6dp
  - &Jellyfin age1d8nx4acd0wsrsk8rkfgvm04vqaal5dcygx5jeumdhsh5s77h234qjxjp0j
  - &Nextcloud age12e9mw8rwsxkqclpcxs3nxcg84l8j8hsxtae5mfn8d9fvnvczw4pqsn8wyf
  - &Nextcloud-Testing age1rjw96c2g46s9qs8s9gy67tz39wm8sq85rzz3cmxvmsgtw32fl43sjegg85
  - &HomeAssistant age1tmsx76qmnw5jp7828vajyq4qdx6lew0t2hcnv58d7dsur84g9qfqey3fyp
  - &ValheimBrueder age19nvp86n9ujxzk0nqw8l5ffnhem7wjxcv32kf9nhfq7ax682al59s4g220v
  - &ValheimMarvin age15r4k9est2u4j2zvv9avd4ts0sv7squftxex7wptqa9hyvsdfqcyq6avm29
  - &IonosVPS age1pqd9d8a8p3626uvshcxvdp56cvz95nvx7xygvna5lvnrkp4s03uq9xz5kd
  - &JuliansPC age1ts4z7k5ahqzn9f7qpkdjta8kvjfl8rke2zxp3wlusps9xngyv9eqh3zucz
  - &JuliansFramework age18c4fpcl6mvedfudppdammfg4cmfcemxc98nq733l7h76apdgmsnq939yaz
  - &mainserver age16zwdpg2e4p9ct85xch7zl69nl7tnedwnt4dcxzu7f30d2rwqufqsuy8q6n
creation_rules:
  - path_regex: ^secrets/JuliansFramework/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
  - path_regex: ^secrets/JuliansPC/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansPC
  - path_regex: ^secrets/mainserver/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *mainserver
  - path_regex: ^secrets/IonosVPS/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *IonosVPS
  - path_regex: ^secrets/Nextcloud/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Nextcloud
  - path_regex: ^secrets/Nextcloud-Testing/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Nextcloud-Testing
  - path_regex: ^secrets/Jellyfin/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Jellyfin
  - path_regex: ^secrets/ValheimBrueder/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *ValheimBrueder
  - path_regex: ^secrets/ValheimMarvin/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *ValheimMarvin
  - path_regex: ^secrets/Kanidm/Nextcloud-Testing_client-secret.yaml$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Kanidm
      - *Nextcloud-Testing
  - path_regex: ^secrets/Kanidm/Nextcloud_client-secret.yaml$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Kanidm
      - *Nextcloud
  - path_regex: ^secrets/Kanidm/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Kanidm
  - path_regex: ^secrets/Email/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Email
  - path_regex: ^secrets/HomeAssistant/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *HomeAssistant
  - path_regex: ^secrets/backupServerOffsite/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *backupServerOffsite
  - path_regex: ^secrets/IonosVPS2/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *IonosVPS2
  - path_regex: ^secrets/backupServer/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *backupServer
  - path_regex: ^secrets/[^/]*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
      - *JuliansPC
      - *mainserver
      - *IonosVPS
      - *Nextcloud
      - *Nextcloud-Testing
      - *Jellyfin
      - *ValheimBrueder
      - *ValheimMarvin
      - *Kanidm
      - *Email
      - *HomeAssistant
      - *backupServerOffsite
      - *IonosVPS2
      - *backupServer
  - key_groups:
    - pgp:
      - *yubikey
