keys:
  - &yubikey 3843C723C748227138A7EAA4F22E9E9D8F5CCE04
  - &Jellyfin age1d8nx4acd0wsrsk8rkfgvm04vqaal5dcygx5jeumdhsh5s77h234qjxjp0j
  - &Nextcloud age12e9mw8rwsxkqclpcxs3nxcg84l8j8hsxtae5mfn8d9fvnvczw4pqsn8wyf
  - &Nextcloud-Testing age1rjw96c2g46s9qs8s9gy67tz39wm8sq85rzz3cmxvmsgtw32fl43sjegg85
  - &ValheimBrueder age19nvp86n9ujxzk0nqw8l5ffnhem7wjxcv32kf9nhfq7ax682al59s4g220v
  - &ValheimMarvin age15r4k9est2u4j2zvv9avd4ts0sv7squftxex7wptqa9hyvsdfqcyq6avm29
  - &IonosVPS age1pqd9d8a8p3626uvshcxvdp56cvz95nvx7xygvna5lvnrkp4s03uq9xz5kd
  - &JuliansPC age1ts4z7k5ahqzn9f7qpkdjta8kvjfl8rke2zxp3wlusps9xngyv9eqh3zucz
  - &JuliansFramework age18c4fpcl6mvedfudppdammfg4cmfcemxc98nq733l7h76apdgmsnq939yaz
  - &mainserver age16zwdpg2e4p9ct85xch7zl69nl7tnedwnt4dcxzu7f30d2rwqufqsuy8q6n
creation_rules:
  - path_regex: ^secrets/JuliansFramework/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
  - path_regex: ^secrets/JuliansPC/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansPC
  - path_regex: ^secrets/mainserver/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *mainserver
  - path_regex: ^secrets/IonosVPS/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *IonosVPS
  - path_regex: ^secrets/Nextcloud/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Nextcloud
  - path_regex: ^secrets/Nextcloud-Testing/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Nextcloud-Testing
  - path_regex: ^secrets/Jellyfin/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *Jellyfin
  - path_regex: ^secrets/ValheimBrueder/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *ValheimBrueder
  - path_regex: ^secrets/ValheimMarvin/.*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *ValheimMarvin
  - path_regex: ^secrets/[^/]*$
    key_groups:
    - pgp:
      - *yubikey
      age:
      - *JuliansFramework
      - *JuliansPC
      - *mainserver
      - *IonosVPS
      - *Nextcloud
      - *Nextcloud-Testing
      - *Jellyfin
      - *ValheimBrueder
      - *ValheimMarvin
  - key_groups:
    - pgp:
      - *yubikey
