{
 "title": "cAdvisor",
 "description": "Systemd services & NixOS containers CPU, memory and networking monitoring. This is a modified version of https://grafana.com/grafana/dashboards/193-docker-monitoring/",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(cadvisor_version_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Running Systemd services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{id=~\"/system.slice/.*service\", instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "Running NixOS containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{id=~\"^/machine.slice/.*service$\", id!~\"^.*[.]service.+$\", instance=\"$node\"})"
    }
   ]
  },
  {
   "title": "CPU -  Systemd services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{id=~\"/system.slice/.*service\", instance=\"$node\"}[$__rate_interval]) * 100)"
    }
   ]
  },
  {
   "title": "CPU - NixOS containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{id=~\"^/machine.slice/.*service$\", id!~\"^.*[.]service.+$\", instance=\"$node\"}[$__rate_interval]) * 100)"
    }
   ]
  },
  {
   "title": "RAM - Systemd services",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id=~\"/system.slice/.*service\", instance=\"$node\"})/1024/1024"
    }
   ]
  },
  {
   "title": "RAM - NixOS Containers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{id=~\"^/machine.slice/.*service$\", id!~\"^.*[.]service.+$\", instance=\"$node\"})/1024/1024"
    }
   ]
  },
  {
   "title": "CPU Single core - Systemd services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{id=~\"/system.slice/.*service\", instance=\"$node\"}[$__rate_interval]) * 100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "CPU Single core - NixOS containers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{id=~\"^/machine.slice/.*service$\", id!~\"^.*[.]service.+$\", instance=\"$node\"}[$__rate_interval]) * 100",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory Usage - Systemd services",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"/system.slice/.*service\", instance=\"$node\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Memory Usage - NixOS containers",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{id=~\"^/machine.slice/.*service$\", id!~\"^.*[.]service.+$\", instance=\"$node\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Network Rx - NixOS container private network interfaces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{interface=~\"ve-.*\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Network Tx - NixOS container private network interfaces",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{interface=~\"ve-.*\", instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{interface}}"
    }
   ]
  }
 ]
}