{
 "title": "Zfs (Node exporter)",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(node_zfs_zpool_state,zpool)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pool state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_zpool_state{instance=\"$node\", zpool=\"$pool\"} == 1",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Reads & Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_zfs_zpool_dataset_nread{instance=\"$node\", zpool=\"$pool\", dataset=\"$pool\"}[$__rate_interval])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(node_zfs_zpool_dataset_nwritten{instance=\"$node\", zpool=\"$pool\", dataset=\"$pool\"}[$__rate_interval])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Pool used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{fstype=\"zfs\", instance=\"$node\", device=\"$pool\"} * 100) / node_filesystem_size_bytes{fstype=\"zfs\", instance=\"$node\", device=\"$pool\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arc memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_zfs_arc_size{instance=\"$node\"} / node_memory_MemTotal_bytes{instance=\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Arc sizes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_zfs_arc_size{instance=\"$node\"}",
     "legendFormat": "Arc size"
    },
    {
     "expr": "node_zfs_arc_l2_size{instance=\"$node\"}",
     "legendFormat": "Arc L2 size"
    }
   ]
  },
  {
   "title": "Arc Hits & Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(node_zfs_arc_hits{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "Hits"
    },
    {
     "expr": "rate(node_zfs_arc_misses{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "Misses"
    },
    {
     "expr": "rate(node_zfs_arc_l2_hits{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "L2 Hits"
    },
    {
     "expr": "rate(node_zfs_arc_l2_misses{instance=\"$node\"}[$__rate_interval])",
     "legendFormat": "L2 Misses"
    }
   ]
  }
 ]
}